### PR TITLE
cleaned up master app.js file

### PR DESCRIPTION
**Pull request by corejola**
Clean up of the Javascript file for the Master Branch. Removed the console logs & unnecessary comments.

Next Issues are:
- Issue #3 - User Input Zip Code converted to Latitude & Longitude Nancy
- Issue #4 - Display Store Locator Stores as markers on Google Maps API - Ben & Lorraine 
- Issue #5 - Display Store Locator onto side bar HTML Cedric

### CODE REVIEW

**Review by Benk0033 — CHANGES_REQUESTED** [review]
We need the code from lines 109-132 to show the markers right?

**Comment by corejola** [comment]
updated the clean up master file will perform another pull request

**Comment by corejola** [comment]
Team, I am reopening this pull request because the file is correct, the map markers function was not deleted and were just hidden. Be sure to review the code lines.

**Review by lorrainebaynosa — APPROVED** [review]
Code looks good.

**Review by Benk0033 — APPROVED** [review]
reviewed and approved

**Comment by corejola** [comment]
Following Issues:
Issue #15
Issue #3 
Issue #4

**Pull request merged**
