### PR TITLE
Revised Bugfix/misc

### PR DESCRIPTION
**Pull request by Benk0033**
Found a bug in the bugfix so that is fixed now as well. Fixed bug where only one marker was showing after search and confirmed jQuery for showing locations list is working. Placeholder/workaround for showing retailer/product name was added. Also updated comments for more clarity.

### CODE REVIEW

**Comment by corejola** [comment]
Functionality is working with no noticeable bugs. The code looks clean and good use of comments for code notes. Once reviewed by the rest of the team I am good to merge this code into the master.

**Comment by lorrainebaynosa** [comment]
Tested on VS code. Looks good. Tested with different zip codes. Great job, Ben!

**Comment by NanceCA** [comment]
Looks good to me as well. Excellent job Ben! Thank you for tackling that bug- it was hard for me to find!

**Comment by corejola** [comment]
current fix includes work around for issue #15 & #27 

ongoing issues #25 #26

**Pull request merged**
